In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import tensorflow as tf
from tensorboard.notebook import display

In [40]:
data_raw = pd.read_csv("C:/PGDAI/Programming Language AI/CA70/BankFraud/Base.csv")
pd.set_option('display.max_columns', None)
display(data_raw)
display(data_raw.describe(include='all'))
print(data_raw.info())


TypeError: %d format: a real number is required, not DataFrame

In [9]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the numerical columns
data1[numerical_columns] = scaler.fit_transform(data1[numerical_columns])

# Check the scaled values
print(data1[numerical_columns].head())

   fraud_bool  income  zip_count_4w   velocity_6h  velocity_24h  velocity_4w  \
0           0     0.3          1059  13096.035018   7850.955007  6742.080561   
1           0     0.8          1658   9223.283431   5745.251481  5941.664859   
2           0     0.8          1095   4471.472149   5471.988958  5992.555113   
3           0     0.6          3483  14431.993621   6755.344479  5970.336831   
4           0     0.9          2339   7601.511579   5124.046930  5940.734212   

   bank_branch_count_8w  date_of_birth_distinct_emails_4w  credit_risk_score  \
0                     5                                 5                163   
1                     3                                18                154   
2                    15                                11                 89   
3                    11                                13                 90   
4                     1                                 6                 91   

   email_is_free  has_other_cards  pro

In [6]:
data1 = data_raw[['fraud_bool', 
                  'income', 
                  'payment_type', 
                  'zip_count_4w', 
                  'velocity_6h', 
                  'velocity_24h', 
                  'velocity_4w', 
                  'bank_branch_count_8w',
                  'date_of_birth_distinct_emails_4w', 
                  'credit_risk_score', 
                  'email_is_free', 
                  'has_other_cards', 
                  'proposed_credit_limit',
                  'foreign_request', 
                  'device_fraud_count', 
                  'month', 
                  'name_email_similarity', 
                  'prev_address_months_count',
                  'customer_age', 
                  'days_since_request', 
                  'session_length_in_minutes', 
                  'employment_status', 
                  'housing_status']].copy()

In [7]:
display(data1)

fraud_bool  income payment_type  zip_count_4w   velocity_6h  \
0                0     0.3           AA          1059  13096.035018   
1                0     0.8           AD          1658   9223.283431   
2                0     0.8           AB          1095   4471.472149   
3                0     0.6           AB          3483  14431.993621   
4                0     0.9           AA          2339   7601.511579   
...            ...     ...          ...           ...           ...   
999995           0     0.8           AB           530   6732.602414   
999996           0     0.9           AC           408   1574.293294   
999997           0     0.8           AA           749   1258.864938   
999998           0     0.9           AB           707   7048.137128   
999999           0     0.6           AA           655   3737.076479   

        velocity_24h  velocity_4w  bank_branch_count_8w  \
0        7850.955007  6742.080561                     5   
1        5745.251481  5941.664859                     3   
2        5471.988958  5992.555113                    15   
3        6755.344479  5970.336831                    11   
4        5124.046930  5940.734212                     1   
...              ...          ...                   ...   
999995   3010.048099  3095.754245                    42   
999996   2716.495767  4286.089050                     0   
999997   3601.322892  3103.891664                     2   
999998   6521.395012  3068.265084                     7   
999999   3135.788094  3051.003293                    14   

        date_of_birth_distinct_emails_4w  credit_risk_score  email_is_free  \
0                                      5                163              1   
1                                     18                154              1   
2                                     11                 89              1   
3                                     13                 90              1   
4                                      6                 91              0   
...                                  ...                ...            ...   
999995                                 8                305              1   
999996                                 5                235              0   
999997                                 3                195              1   
999998                                 8                148              0   
999999                                 8                100              1   

        has_other_cards  proposed_credit_limit  foreign_request  \
0                     0                 1500.0                0   
1                     0                 1500.0                0   
2                     0                  200.0                0   
3                     0                  200.0                0   
4                     0                  200.0                0   
...                 ...                    ...              ...   
999995                0                 1500.0                0   
999996                1                 1000.0                0   
999997                0                  200.0                0   
999998                0                  200.0                0   
999999                1                  200.0                0   

        device_fraud_count  month  name_email_similarity  \
0                        0      0               0.986506   
1                        0      0               0.617426   
2                        0      0               0.996707   
3                        0      0               0.475100   
4                        0      0               0.842307   
...                    ...    ...                    ...   
999995                   0      7               0.124690   
999996                   0      7               0.824544   
999997                   0      7               0.140891   
999998                   0      7               0.002480   
999999                   0      7           

In [8]:
print(data1.isnull().sum())

fraud_bool                          0
income                              0
payment_type                        0
zip_count_4w                        0
velocity_6h                         0
velocity_24h                        0
velocity_4w                         0
bank_branch_count_8w                0
date_of_birth_distinct_emails_4w    0
credit_risk_score                   0
email_is_free                       0
has_other_cards                     0
proposed_credit_limit               0
foreign_request                     0
device_fraud_count                  0
month                               0
name_email_similarity               0
prev_address_months_count           0
customer_age                        0
days_since_request                  0
session_length_in_minutes           0
employment_status                   0
housing_status                      0
dtype: int64


In [10]:
data1_encoded = pd.get_dummies(data1, columns=['payment_type', 'employment_status'], drop_first=True)
print(data1_encoded.head())

   fraud_bool  income  zip_count_4w   velocity_6h  velocity_24h  velocity_4w  \
0           0     0.3          1059  13096.035018   7850.955007  6742.080561   
1           0     0.8          1658   9223.283431   5745.251481  5941.664859   
2           0     0.8          1095   4471.472149   5471.988958  5992.555113   
3           0     0.6          3483  14431.993621   6755.344479  5970.336831   
4           0     0.9          2339   7601.511579   5124.046930  5940.734212   

   bank_branch_count_8w  date_of_birth_distinct_emails_4w  credit_risk_score  \
0                     5                                 5                163   
1                     3                                18                154   
2                    15                                11                 89   
3                    11                                13                 90   
4                     1                                 6                 91   

   email_is_free  has_other_cards  pro

In [19]:
numerical_columns = data1.select_dtypes(include=['number']).columns
numerical_columns = [col for col in data1.columns if data1[col].dtype in ['int64', 'float64'] and data1[col].dtype != 'bool']
print(numerical_columns)

['fraud_bool', 'income', 'zip_count_4w', 'velocity_6h', 'velocity_24h', 'velocity_4w', 'bank_branch_count_8w', 'date_of_birth_distinct_emails_4w', 'credit_risk_score', 'email_is_free', 'has_other_cards', 'proposed_credit_limit', 'foreign_request', 'device_fraud_count', 'month', 'name_email_similarity', 'prev_address_months_count', 'customer_age', 'days_since_request', 'session_length_in_minutes']


In [20]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the numerical columns
data1[numerical_columns] = scaler.fit_transform(data1[numerical_columns])

# Check the scaled values
print(data1[numerical_columns].head())

   fraud_bool  income  zip_count_4w  velocity_6h  velocity_24h  velocity_4w  \
0         0.0   0.250      0.157934     0.785651      0.798218     0.939390   
1         0.0   0.875      0.247350     0.556307      0.541631     0.747399   
2         0.0   0.875      0.163308     0.274904      0.508333     0.759605   
3         0.0   0.625      0.519779     0.864767      0.664714     0.754276   
4         0.0   1.000      0.349007     0.460265      0.465935     0.747175   

   bank_branch_count_8w  date_of_birth_distinct_emails_4w  credit_risk_score  \
0              0.002096                          0.128205           0.595707   
1              0.001258                          0.461538           0.579606   
2              0.006289                          0.282051           0.463327   
3              0.004612                          0.333333           0.465116   
4              0.000419                          0.153846           0.466905   

   email_is_free  has_other_cards  proposed_

In [22]:
from sklearn.preprocessing import StandardScaler

# Assuming 'data1' is your DataFrame with numerical features
# Let's select only the numerical columns for scaling
numerical_columns = ['fraud_bool', 'income', 'zip_count_4w', 'velocity_6h', 'velocity_24h', 'velocity_4w', 'bank_branch_count_8w', 'date_of_birth_distinct_emails_4w', 'credit_risk_score', 'email_is_free', 'has_other_cards', 'proposed_credit_limit', 'foreign_request', 'device_fraud_count', 'month', 'name_email_similarity', 'prev_address_months_count', 'customer_age', 'days_since_request', 'session_length_in_minutes']

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform the numerical columns
data1[numerical_columns] = scaler.fit_transform(data1[numerical_columns])

# Check the scaled values
print(data1[numerical_columns].head())

   fraud_bool    income  zip_count_4w  velocity_6h  velocity_24h  velocity_4w  \
0   -0.105603 -0.904778     -0.510946     2.469193      2.082983     2.050084   
1   -0.105603  0.817326      0.084852     1.182299      0.659452     1.179919   
2   -0.105603  0.817326     -0.475139    -0.396701      0.474717     1.235244   
3   -0.105603  0.128484      1.900097     2.913125      1.342311     1.211090   
4   -0.105603  1.161747      0.762212     0.643393      0.239496     1.178907   

   bank_branch_count_8w  date_of_birth_distinct_emails_4w  credit_risk_score  \
0             -0.390235                         -0.894663           0.459380   
1             -0.394586                          1.687885           0.330221   
2             -0.368478                          0.297282          -0.602591   
3             -0.377181                          0.694597          -0.588240   
4             -0.398938                         -0.696005          -0.573889   

   email_is_free  has_other_card

In [36]:
from keras.layers import Input, Dense
from keras.models import Model

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

np.random.seed(42)
n_samples = 1000
X = np.random.rand(n_samples, 10)  # 10 feature columns
y = np.random.randint(0, 2, size=(700,))
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Define the autoencoder architecture
input_layer = Input(shape=(X_train.shape[1],))
encoded = Dense(64, activation='relu')(input_layer)
decoded = Dense(X_train.shape[1], activation='sigmoid')(encoded)

autoencoder = Model(input_layer, decoded)

# Compile and train the autoencoder
autoencoder.compile(optimizer='adam', loss='mean_squared_error')
autoencoder.fit(X_train, X_train, epochs=50, batch_size=256, shuffle=True)

# Use the encoder to reduce the feature set
encoder = Model(input_layer, encoded)
encoded_features = encoder.predict(X_train)

ValueError: Found input variables with inconsistent numbers of samples: [1000, 700]

In [34]:
print(encoded_features)

[[0.32865372 0.         0.36263973 ... 0.         0.28957978 0.27729884]
 [0.54896784 0.         0.35542533 ... 0.         0.06976905 0.21287186]
 [0.34068018 0.         0.3020246  ... 0.         0.16435385 0.28577185]
 ...
 [0.2806155  0.         0.6922711  ... 0.         0.06481639 0.42114156]
 [0.26239705 0.         0.         ... 0.         0.30421352 0.30941528]
 [0.64203656 0.         0.35216728 ... 0.         0.2834203  0.63340145]]


In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
encoded_features_reshaped = np.expand_dims(encoded_features, axis=-1)  # shape (1000, 50, 1, 1)

# Now, the data is in the shape that the CNN expects: (samples, height, width, channels)

# Build a simple CNN model for this 1D feature data
# Build the CNN model
model = Sequential()

# First Conv2D layer with kernel size (3, 1) for 1D-like data
model.add(Conv2D(64, kernel_size=(3, 1), activation='relu', input_shape=(64, 1, 1)))

# Max pooling layer
model.add(MaxPooling2D(pool_size=(2, 1)))

# Flatten the output from Conv2D
model.add(Flatten())

# Now, let's check the shape of the output after Flatten
model.summary()

# Add Dense layer
model.add(Dense(128, activation='relu'))  # Example for fully connected layer
model.add(Dense(1, activation='sigmoid'))  # Binary classification output layer

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Example labels
labels = np.random.randint(0, 2, size=(1000,))  # Example binary labels

# Train the model
model.fit(encoded_features, labels, epochs=10, batch_size=32)

C:\Users\cheta\PycharmProjects\Synthetic_Dataset\.venv\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_5 (Conv2D)               │ (None, 62, 1, 64)      │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 31, 1, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (None, 1984)           │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256 (1.00 KB)

 Trainable params: 256 (1.00 KB)

 Non-trainable params: 0 (0.00 B)

ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 700
'y' sizes: 1000
